<?php

namespace App\Rbac;

/**
 * Les dix-neuf rôles gabarits du § 4 de ROLES_ET_PERMISSIONS.md, avec leurs permissions
 * et la portée de chacune.
 *
 * Lecture des symboles des matrices du § 5 :
 *   `●` → portée `all` pour un rôle plateforme, `compagnie` pour un rôle compagnie ;
 *   `◐` → `gare` pour les rôles de terrain (chef de gare, guichetier, agent, bagagiste),
 *          `own` pour le chauffeur et pour les actions limitées à ses propres ventes,
 *          `compagnie` pour les rôles de siège, dont le `◐` encode une restriction métier
 *          (plafond de montant, type de document, règle des quatre yeux) appliquée par les
 *          policies et non par la portée ;
 *   `○` → la permission de lecture correspondante, en portée `compagnie` ;
 *   `—` → absente.
 *
 * Le `rang` sert à la règle d'attribution « on n'attribue qu'un rôle de rang strictement
 * inférieur au sien ».
 */
class RoleGabarits
{
    /**
     * @return list<array{name: string, label: string, scope: string, rang: int, description: string, permissions: array<string, string>}>
     */
    public static function tous(): array
    {
        return [
            [
                'name' => 'root',
                'label' => 'Super Administrateur',
                'scope' => 'platform',
                'rang' => 100,
                'description' => 'Compte technique LIPTRA : référentiels, création de compagnies, paramètres globaux.',
                'permissions' => [
                    'platform.audit.view' => 'all',
                    'platform.compagnie.activate' => 'all',
                    'platform.compagnie.create' => 'all',
                    'platform.compagnie.delete' => 'all',
                    'platform.compagnie.suspend' => 'all',
                    'platform.compagnie.update' => 'all',
                    'platform.compagnie.view' => 'all',
                    'platform.pays.manage' => 'all',
                    'platform.region.manage' => 'all',
                    'platform.settings.manage' => 'all',
                    'platform.stats.view' => 'all',
                    'platform.user.impersonate' => 'all',
                    'platform.user.suspend' => 'all',
                    'platform.user.update' => 'all',
                    'platform.user.view' => 'all',
                    'platform.ville.manage' => 'all',
                ],
            ],
            [
                'name' => 'platform_admin',
                'label' => 'Administrateur plateforme',
                'scope' => 'platform',
                'rang' => 90,
                'description' => 'Exploitation courante de la plateforme, sans accès aux secrets ni usurpation d\'identité.',
                'permissions' => [
                    'platform.audit.view' => 'all',
                    'platform.compagnie.activate' => 'all',
                    'platform.compagnie.create' => 'all',
                    'platform.compagnie.suspend' => 'all',
                    'platform.compagnie.update' => 'all',
                    'platform.compagnie.view' => 'all',
                    'platform.pays.manage' => 'all',
                    'platform.region.manage' => 'all',
                    'platform.settings.manage' => 'all',
                    'platform.stats.view' => 'all',
                    'platform.user.suspend' => 'all',
                    'platform.user.update' => 'all',
                    'platform.user.view' => 'all',
                    'platform.ville.manage' => 'all',
                ],
            ],
            [
                'name' => 'platform_support',
                'label' => 'Support & Modération',
                'scope' => 'platform',
                'rang' => 50,
                'description' => 'Assistance aux voyageurs et aux compagnies, modération du contenu. Aucune écriture financière.',
                'permissions' => [
                    'client.fidelite.view.own' => 'all',
                    'client.post.comment' => 'all',
                    'client.profil.view' => 'all',
                    'client.ticket.pdf' => 'all',
                    'client.ticket.regenerate' => 'all',
                    'client.ticket.view.own' => 'all',
                    'platform.audit.view' => 'all',
                    'platform.compagnie.view' => 'all',
                    'platform.stats.view' => 'all',
                    'platform.user.view' => 'all',
                ],
            ],
            [
                'name' => 'client',
                'label' => 'Voyageur',
                'scope' => 'platform',
                'rang' => 0,
                'description' => 'Rôle par défaut de tout compte créé depuis l\'application ou le site.',
                'permissions' => [
                    'client.bugreport.create' => 'own',
                    'client.conversation.create' => 'own',
                    'client.fidelite.view.own' => 'own',
                    'client.notification.manage' => 'own',
                    'client.paiement.initiate' => 'own',
                    'client.post.comment' => 'own',
                    'client.post.like' => 'own',
                    'client.profil.update' => 'own',
                    'client.profil.view' => 'own',
                    'client.rating.create' => 'own',
                    'client.ticket.buy' => 'own',
                    'client.ticket.buyForOther' => 'own',
                    'client.ticket.changeDate' => 'own',
                    'client.ticket.pause' => 'own',
                    'client.ticket.pdf' => 'own',
                    'client.ticket.regenerate' => 'own',
                    'client.ticket.transfer' => 'own',
                    'client.ticket.view.own' => 'own',
                ],
            ],
            [
                'name' => 'compagnie_dg',
                'label' => 'Direction Générale',
                'scope' => 'compagnie',
                'rang' => 80,
                'description' => 'Direction de la compagnie. Ne vend pas au guichet : une vente doit être imputée à une session de caisse nominative.',
                'permissions' => [
                    'caisse.ecart.validate' => 'compagnie',
                    'caisse.historique.export' => 'compagnie',
                    'caisse.historique.view' => 'compagnie',
                    'caisse.session.forceClose' => 'compagnie',
                    'caisse.session.view.all' => 'compagnie',
                    'caisse.session.view.gare' => 'gare',
                    'compagnie.dashboard.view' => 'compagnie',
                    'compagnie.gare.assignUser' => 'compagnie',
                    'compagnie.parametres.reset' => 'compagnie',
                    'compagnie.parametres.update' => 'compagnie',
                    'compagnie.parametres.updateAdvanced' => 'compagnie',
                    'compagnie.parametres.view' => 'compagnie',
                    'compagnie.profil.update' => 'compagnie',
                    'compagnie.profil.view' => 'compagnie',
                    'compagnie.role.assign' => 'compagnie',
                    'compagnie.role.manage' => 'compagnie',
                    'compagnie.user.create' => 'compagnie',
                    'compagnie.user.disable' => 'compagnie',
                    'compagnie.user.resetPassword' => 'compagnie',
                    'compagnie.user.update' => 'compagnie',
                    'compagnie.user.view' => 'compagnie',
                    'contenu.article.create' => 'compagnie',
                    'contenu.article.delete' => 'compagnie',
                    'contenu.article.publish' => 'compagnie',
                    'contenu.article.update' => 'compagnie',
                    'contenu.article.view' => 'compagnie',
                    'contenu.categorie.manage' => 'compagnie',
                    'contenu.commentaire.moderate' => 'compagnie',
                    'contenu.tag.manage' => 'compagnie',
                    'crm.bugreport.triage' => 'compagnie',
                    'crm.bugreport.view' => 'compagnie',
                    'crm.conversation.assign' => 'compagnie',
                    'crm.conversation.close' => 'compagnie',
                    'crm.conversation.reply' => 'compagnie',
                    'crm.conversation.view' => 'compagnie',
                    'crm.fidelite.adjust' => 'compagnie',
                    'crm.fidelite.view' => 'compagnie',
                    'crm.rating.reply' => 'compagnie',
                    'crm.rating.report' => 'compagnie',
                    'crm.rating.view' => 'compagnie',
                    'embarquement.conflit.resolve' => 'compagnie',
                    'embarquement.conflit.view' => 'compagnie',
                    'embarquement.manifeste.view' => 'compagnie',
                    'finance.bilan.view' => 'compagnie',
                    'finance.categorie.manage' => 'compagnie',
                    'finance.depense.approve' => 'compagnie',
                    'finance.depense.create' => 'compagnie',
                    'finance.depense.delete' => 'compagnie',
                    'finance.depense.update' => 'compagnie',
                    'finance.depense.view' => 'compagnie',
                    'finance.promo.create' => 'compagnie',
                    'finance.promo.deactivate' => 'compagnie',
                    'finance.promo.update' => 'compagnie',
                    'finance.promo.view' => 'compagnie',
                    'finance.rapport.export' => 'compagnie',
                    'finance.rapport.view' => 'compagnie',
                    'finance.recette.delete' => 'compagnie',
                    'finance.recette.view' => 'compagnie',
                    'finance.remboursement.approve' => 'compagnie',
                    'finance.remboursement.request' => 'compagnie',
                    'guichet.reservation.hold' => 'compagnie',
                    'guichet.siege.reassign' => 'compagnie',
                    'guichet.ticket.block' => 'compagnie',
                    'guichet.ticket.cancel' => 'compagnie',
                    'guichet.ticket.changeDate' => 'compagnie',
                    'guichet.ticket.export' => 'compagnie',
                    'guichet.ticket.pause' => 'compagnie',
                    'guichet.ticket.print' => 'compagnie',
                    'guichet.ticket.reprint' => 'compagnie',
                    'guichet.ticket.transfer' => 'compagnie',
                    'guichet.ticket.unblock' => 'compagnie',
                    'guichet.ticket.view.all' => 'compagnie',
                    'guichet.ticket.view.gare' => 'gare',
                    'reseau.chauffeur.create' => 'compagnie',
                    'reseau.chauffeur.delete' => 'compagnie',
                    'reseau.chauffeur.update' => 'compagnie',
                    'reseau.chauffeur.view' => 'compagnie',
                    'reseau.document.delete' => 'compagnie',
                    'reseau.document.manageRappel' => 'compagnie',
                    'reseau.document.upload' => 'compagnie',
                    'reseau.document.view' => 'compagnie',
                    'reseau.gare.create' => 'compagnie',
                    'reseau.gare.delete' => 'compagnie',
                    'reseau.gare.setDefault' => 'compagnie',
                    'reseau.gare.update' => 'compagnie',
                    'reseau.gare.view' => 'compagnie',
                    'reseau.vehicule.create' => 'compagnie',
                    'reseau.vehicule.delete' => 'compagnie',
                    'reseau.vehicule.setStatut' => 'compagnie',
                    'reseau.vehicule.update' => 'compagnie',
                    'reseau.vehicule.view' => 'compagnie',
                    'voyage.classe.manage' => 'compagnie',
                    'voyage.confort.manage' => 'compagnie',
                    'voyage.instance.assignChauffeur' => 'compagnie',
                    'voyage.instance.assignVehicule' => 'compagnie',
                    'voyage.instance.cancel' => 'compagnie',
                    'voyage.instance.close' => 'compagnie',
                    'voyage.instance.generate' => 'compagnie',
                    'voyage.instance.update' => 'compagnie',
                    'voyage.instance.view' => 'compagnie',
                    'voyage.tarif.update' => 'compagnie',
                    'voyage.trajet.create' => 'compagnie',
                    'voyage.trajet.delete' => 'compagnie',
                    'voyage.trajet.update' => 'compagnie',
                    'voyage.trajet.view' => 'compagnie',
                    'voyage.voyage.create' => 'compagnie',
                    'voyage.voyage.delete' => 'compagnie',
                    'voyage.voyage.publish' => 'compagnie',
                    'voyage.voyage.update' => 'compagnie',
                    'voyage.voyage.view' => 'compagnie',
                ],
            ],
            [
                'name' => 'compagnie_admin',
                'label' => 'Administrateur Compagnie',
                'scope' => 'compagnie',
                'rang' => 70,
                'description' => 'Délégué de la direction sur la configuration et l\'équipe.',
                'permissions' => [
                    'caisse.ecart.validate' => 'compagnie',
                    'caisse.historique.export' => 'compagnie',
                    'caisse.historique.view' => 'compagnie',
                    'caisse.session.forceClose' => 'compagnie',
                    'caisse.session.view.all' => 'compagnie',
                    'caisse.session.view.gare' => 'gare',
                    'compagnie.dashboard.view' => 'compagnie',
                    'compagnie.gare.assignUser' => 'compagnie',
                    'compagnie.parametres.update' => 'compagnie',
                    'compagnie.parametres.view' => 'compagnie',
                    'compagnie.profil.update' => 'compagnie',
                    'compagnie.profil.view' => 'compagnie',
                    'compagnie.role.assign' => 'compagnie',
                    'compagnie.user.create' => 'compagnie',
                    'compagnie.user.disable' => 'compagnie',
                    'compagnie.user.resetPassword' => 'compagnie',
                    'compagnie.user.update' => 'compagnie',
                    'compagnie.user.view' => 'compagnie',
                    'contenu.article.create' => 'compagnie',
                    'contenu.article.delete' => 'compagnie',
                    'contenu.article.publish' => 'compagnie',
                    'contenu.article.update' => 'compagnie',
                    'contenu.article.view' => 'compagnie',
                    'contenu.categorie.manage' => 'compagnie',
                    'contenu.commentaire.moderate' => 'compagnie',
                    'contenu.tag.manage' => 'compagnie',
                    'crm.bugreport.triage' => 'compagnie',
                    'crm.bugreport.view' => 'compagnie',
                    'crm.conversation.assign' => 'compagnie',
                    'crm.conversation.close' => 'compagnie',
                    'crm.conversation.reply' => 'compagnie',
                    'crm.conversation.view' => 'compagnie',
                    'crm.fidelite.adjust' => 'compagnie',
                    'crm.fidelite.view' => 'compagnie',
                    'crm.rating.reply' => 'compagnie',
                    'crm.rating.report' => 'compagnie',
                    'crm.rating.view' => 'compagnie',
                    'embarquement.conflit.resolve' => 'compagnie',
                    'embarquement.conflit.view' => 'compagnie',
                    'embarquement.manifeste.view' => 'compagnie',
                    'finance.bilan.view' => 'compagnie',
                    'finance.categorie.manage' => 'compagnie',
                    'finance.depense.approve' => 'compagnie',
                    'finance.depense.create' => 'compagnie',
                    'finance.depense.update' => 'compagnie',
                    'finance.depense.view' => 'compagnie',
                    'finance.promo.create' => 'compagnie',
                    'finance.promo.deactivate' => 'compagnie',
                    'finance.promo.update' => 'compagnie',
                    'finance.promo.view' => 'compagnie',
                    'finance.rapport.export' => 'compagnie',
                    'finance.rapport.view' => 'compagnie',
                    'finance.recette.view' => 'compagnie',
                    'finance.remboursement.approve' => 'compagnie',
                    'finance.remboursement.request' => 'compagnie',
                    'guichet.reservation.hold' => 'compagnie',
                    'guichet.siege.reassign' => 'compagnie',
                    'guichet.ticket.block' => 'compagnie',
                    'guichet.ticket.cancel' => 'compagnie',
                    'guichet.ticket.changeDate' => 'compagnie',
                    'guichet.ticket.export' => 'compagnie',
                    'guichet.ticket.pause' => 'compagnie',
                    'guichet.ticket.print' => 'compagnie',
                    'guichet.ticket.reprint' => 'compagnie',
                    'guichet.ticket.transfer' => 'compagnie',
                    'guichet.ticket.unblock' => 'compagnie',
                    'guichet.ticket.view.all' => 'compagnie',
                    'guichet.ticket.view.gare' => 'gare',
                    'reseau.chauffeur.create' => 'compagnie',
                    'reseau.chauffeur.delete' => 'compagnie',
                    'reseau.chauffeur.update' => 'compagnie',
                    'reseau.chauffeur.view' => 'compagnie',
                    'reseau.document.delete' => 'compagnie',
                    'reseau.document.manageRappel' => 'compagnie',
                    'reseau.document.upload' => 'compagnie',
                    'reseau.document.view' => 'compagnie',
                    'reseau.gare.create' => 'compagnie',
                    'reseau.gare.delete' => 'compagnie',
                    'reseau.gare.setDefault' => 'compagnie',
                    'reseau.gare.update' => 'compagnie',
                    'reseau.gare.view' => 'compagnie',
                    'reseau.vehicule.create' => 'compagnie',
                    'reseau.vehicule.delete' => 'compagnie',
                    'reseau.vehicule.setStatut' => 'compagnie',
                    'reseau.vehicule.update' => 'compagnie',
                    'reseau.vehicule.view' => 'compagnie',
                    'voyage.classe.manage' => 'compagnie',
                    'voyage.confort.manage' => 'compagnie',
                    'voyage.instance.assignChauffeur' => 'compagnie',
                    'voyage.instance.assignVehicule' => 'compagnie',
                    'voyage.instance.cancel' => 'compagnie',
                    'voyage.instance.close' => 'compagnie',
                    'voyage.instance.generate' => 'compagnie',
                    'voyage.instance.update' => 'compagnie',
                    'voyage.instance.view' => 'compagnie',
                    'voyage.tarif.update' => 'compagnie',
                    'voyage.trajet.create' => 'compagnie',
                    'voyage.trajet.delete' => 'compagnie',
                    'voyage.trajet.update' => 'compagnie',
                    'voyage.trajet.view' => 'compagnie',
                    'voyage.voyage.create' => 'compagnie',
                    'voyage.voyage.delete' => 'compagnie',
                    'voyage.voyage.publish' => 'compagnie',
                    'voyage.voyage.update' => 'compagnie',
                    'voyage.voyage.view' => 'compagnie',
                ],
            ],
            [
                'name' => 'exploitation',
                'label' => 'Responsable Exploitation',
                'scope' => 'compagnie',
                'rang' => 60,
                'description' => 'Offre de voyage, programmation des départs, affectation des véhicules et des chauffeurs.',
                'permissions' => [
                    'caisse.historique.view' => 'compagnie',
                    'caisse.session.view.all' => 'compagnie',
                    'caisse.session.view.gare' => 'gare',
                    'compagnie.dashboard.view' => 'compagnie',
                    'compagnie.gare.assignUser' => 'compagnie',
                    'compagnie.parametres.view' => 'compagnie',
                    'compagnie.profil.view' => 'compagnie',
                    'compagnie.user.view' => 'compagnie',
                    'contenu.article.view' => 'compagnie',
                    'crm.bugreport.view' => 'compagnie',
                    'crm.rating.view' => 'compagnie',
                    'embarquement.conflit.view' => 'compagnie',
                    'embarquement.manifeste.view' => 'compagnie',
                    'finance.bilan.view' => 'compagnie',
                    'finance.depense.create' => 'compagnie',
                    'finance.depense.view' => 'compagnie',
                    'finance.promo.view' => 'compagnie',
                    'finance.rapport.export' => 'compagnie',
                    'finance.rapport.view' => 'compagnie',
                    'finance.recette.view' => 'compagnie',
                    'guichet.ticket.export' => 'compagnie',
                    'guichet.ticket.view.all' => 'compagnie',
                    'guichet.ticket.view.gare' => 'gare',
                    'reseau.chauffeur.create' => 'compagnie',
                    'reseau.chauffeur.update' => 'compagnie',
                    'reseau.chauffeur.view' => 'compagnie',
                    'reseau.document.manageRappel' => 'compagnie',
                    'reseau.document.upload' => 'compagnie',
                    'reseau.document.view' => 'compagnie',
                    'reseau.gare.create' => 'compagnie',
                    'reseau.gare.setDefault' => 'compagnie',
                    'reseau.gare.update' => 'compagnie',
                    'reseau.gare.view' => 'compagnie',
                    'reseau.vehicule.create' => 'compagnie',
                    'reseau.vehicule.setStatut' => 'compagnie',
                    'reseau.vehicule.update' => 'compagnie',
                    'reseau.vehicule.view' => 'compagnie',
                    'voyage.classe.manage' => 'compagnie',
                    'voyage.confort.manage' => 'compagnie',
                    'voyage.instance.assignChauffeur' => 'compagnie',
                    'voyage.instance.assignVehicule' => 'compagnie',
                    'voyage.instance.cancel' => 'compagnie',
                    'voyage.instance.close' => 'compagnie',
                    'voyage.instance.generate' => 'compagnie',
                    'voyage.instance.update' => 'compagnie',
                    'voyage.instance.view' => 'compagnie',
                    'voyage.tarif.update' => 'compagnie',
                    'voyage.trajet.create' => 'compagnie',
                    'voyage.trajet.delete' => 'compagnie',
                    'voyage.trajet.update' => 'compagnie',
                    'voyage.trajet.view' => 'compagnie',
                    'voyage.voyage.create' => 'compagnie',
                    'voyage.voyage.publish' => 'compagnie',
                    'voyage.voyage.update' => 'compagnie',
                    'voyage.voyage.view' => 'compagnie',
                ],
            ],
            [
                'name' => 'chef_gare',
                'label' => 'Chef de Gare',
                'scope' => 'compagnie',
                'rang' => 50,
                'description' => 'Responsable d\'une agence : ventes, caisses, embarquement et personnel de sa gare.',
                'permissions' => [
                    'caisse.ecart.justify' => 'compagnie',
                    'caisse.ecart.validate' => 'gare',
                    'caisse.historique.export' => 'gare',
                    'caisse.historique.view' => 'gare',
                    'caisse.session.close' => 'compagnie',
                    'caisse.session.forceClose' => 'gare',
                    'caisse.session.open' => 'compagnie',
                    'caisse.session.view.gare' => 'gare',
                    'caisse.session.view.own' => 'own',
                    'compagnie.dashboard.view' => 'gare',
                    'compagnie.gare.assignUser' => 'gare',
                    'compagnie.parametres.view' => 'compagnie',
                    'compagnie.profil.view' => 'compagnie',
                    'compagnie.user.resetPassword' => 'gare',
                    'compagnie.user.update' => 'gare',
                    'compagnie.user.view' => 'gare',
                    'contenu.article.view' => 'compagnie',
                    'crm.conversation.assign' => 'gare',
                    'crm.conversation.close' => 'gare',
                    'crm.conversation.reply' => 'gare',
                    'crm.conversation.view' => 'gare',
                    'crm.fidelite.view' => 'gare',
                    'crm.rating.report' => 'gare',
                    'crm.rating.view' => 'gare',
                    'embarquement.app.login' => 'compagnie',
                    'embarquement.bagage.register' => 'compagnie',
                    'embarquement.conflit.view' => 'gare',
                    'embarquement.manifeste.view' => 'compagnie',
                    'embarquement.sync.pull' => 'compagnie',
                    'embarquement.sync.push' => 'compagnie',
                    'embarquement.ticket.block' => 'compagnie',
                    'embarquement.ticket.markAbsent' => 'compagnie',
                    'embarquement.ticket.scan' => 'compagnie',
                    'embarquement.ticket.validate' => 'compagnie',
                    'embarquement.ticket.verifyByPhone' => 'compagnie',
                    'finance.depense.create' => 'gare',
                    'finance.depense.view' => 'gare',
                    'finance.promo.deactivate' => 'gare',
                    'finance.promo.view' => 'compagnie',
                    'finance.rapport.export' => 'gare',
                    'finance.rapport.view' => 'gare',
                    'finance.recette.view' => 'gare',
                    'finance.remboursement.request' => 'compagnie',
                    'guichet.reservation.hold' => 'compagnie',
                    'guichet.siege.reassign' => 'compagnie',
                    'guichet.ticket.block' => 'compagnie',
                    'guichet.ticket.cancel' => 'compagnie',
                    'guichet.ticket.changeDate' => 'compagnie',
                    'guichet.ticket.export' => 'gare',
                    'guichet.ticket.pause' => 'compagnie',
                    'guichet.ticket.print' => 'compagnie',
                    'guichet.ticket.reprint' => 'compagnie',
                    'guichet.ticket.sell' => 'compagnie',
                    'guichet.ticket.transfer' => 'compagnie',
                    'guichet.ticket.unblock' => 'gare',
                    'guichet.ticket.view.gare' => 'gare',
                    'reseau.chauffeur.view' => 'gare',
                    'reseau.document.upload' => 'gare',
                    'reseau.document.view' => 'gare',
                    'reseau.gare.update' => 'gare',
                    'reseau.gare.view' => 'gare',
                    'reseau.vehicule.view' => 'gare',
                    'voyage.instance.assignChauffeur' => 'gare',
                    'voyage.instance.assignVehicule' => 'gare',
                    'voyage.instance.cancel' => 'gare',
                    'voyage.instance.close' => 'gare',
                    'voyage.instance.update' => 'gare',
                    'voyage.instance.view' => 'gare',
                    'voyage.trajet.view' => 'compagnie',
                    'voyage.voyage.view' => 'gare',
                ],
            ],
            [
                'name' => 'guichetier',
                'label' => 'Guichetier',
                'scope' => 'compagnie',
                'rang' => 20,
                'description' => 'Vente au guichet et tenue de sa propre session de caisse. Ne valide jamais son écart.',
                'permissions' => [
                    'caisse.ecart.justify' => 'compagnie',
                    'caisse.historique.view' => 'own',
                    'caisse.session.close' => 'own',
                    'caisse.session.open' => 'compagnie',
                    'caisse.session.view.own' => 'own',
                    'compagnie.dashboard.view' => 'gare',
                    'compagnie.profil.view' => 'compagnie',
                    'contenu.article.view' => 'compagnie',
                    'crm.conversation.view' => 'gare',
                    'crm.fidelite.view' => 'gare',
                    'embarquement.manifeste.view' => 'gare',
                    'embarquement.ticket.verifyByPhone' => 'compagnie',
                    'finance.promo.view' => 'compagnie',
                    'finance.remboursement.request' => 'gare',
                    'guichet.reservation.hold' => 'compagnie',
                    'guichet.siege.reassign' => 'gare',
                    'guichet.ticket.changeDate' => 'gare',
                    'guichet.ticket.pause' => 'gare',
                    'guichet.ticket.print' => 'compagnie',
                    'guichet.ticket.reprint' => 'own',
                    'guichet.ticket.sell' => 'compagnie',
                    'guichet.ticket.transfer' => 'gare',
                    'guichet.ticket.view.gare' => 'gare',
                    'reseau.chauffeur.view' => 'compagnie',
                    'reseau.gare.view' => 'compagnie',
                    'reseau.vehicule.view' => 'compagnie',
                    'voyage.instance.view' => 'gare',
                    'voyage.trajet.view' => 'compagnie',
                    'voyage.voyage.view' => 'gare',
                ],
            ],
            [
                'name' => 'chef_caisse',
                'label' => 'Chef de Caisse',
                'scope' => 'compagnie',
                'rang' => 60,
                'description' => 'Consolidation des caisses, validation des écarts, versements en banque.',
                'permissions' => [
                    'caisse.ecart.justify' => 'compagnie',
                    'caisse.ecart.validate' => 'compagnie',
                    'caisse.historique.export' => 'compagnie',
                    'caisse.historique.view' => 'compagnie',
                    'caisse.session.close' => 'compagnie',
                    'caisse.session.forceClose' => 'compagnie',
                    'caisse.session.open' => 'compagnie',
                    'caisse.session.view.all' => 'compagnie',
                    'caisse.session.view.gare' => 'gare',
                    'caisse.session.view.own' => 'own',
                    'compagnie.dashboard.view' => 'compagnie',
                    'compagnie.parametres.view' => 'compagnie',
                    'compagnie.profil.view' => 'compagnie',
                    'compagnie.user.view' => 'compagnie',
                    'crm.fidelite.view' => 'compagnie',
                    'finance.bilan.view' => 'compagnie',
                    'finance.depense.create' => 'compagnie',
                    'finance.depense.update' => 'compagnie',
                    'finance.depense.view' => 'compagnie',
                    'finance.promo.view' => 'compagnie',
                    'finance.rapport.export' => 'compagnie',
                    'finance.rapport.view' => 'compagnie',
                    'finance.recette.create' => 'compagnie',
                    'finance.recette.update' => 'compagnie',
                    'finance.recette.view' => 'compagnie',
                    'finance.remboursement.request' => 'compagnie',
                    'guichet.ticket.cancel' => 'compagnie',
                    'guichet.ticket.changeDate' => 'compagnie',
                    'guichet.ticket.export' => 'compagnie',
                    'guichet.ticket.print' => 'compagnie',
                    'guichet.ticket.reprint' => 'compagnie',
                    'guichet.ticket.sell' => 'compagnie',
                    'guichet.ticket.view.all' => 'compagnie',
                    'guichet.ticket.view.gare' => 'gare',
                    'reseau.gare.view' => 'compagnie',
                    'voyage.instance.view' => 'compagnie',
                    'voyage.trajet.view' => 'compagnie',
                    'voyage.voyage.view' => 'compagnie',
                ],
            ],
            [
                'name' => 'agent_embarquement',
                'label' => 'Agent d\'Embarquement',
                'scope' => 'compagnie',
                'rang' => 20,
                'description' => 'Contrôle et validation des tickets au quai, y compris hors connexion.',
                'permissions' => [
                    'compagnie.profil.view' => 'compagnie',
                    'embarquement.app.login' => 'compagnie',
                    'embarquement.bagage.register' => 'gare',
                    'embarquement.manifeste.view' => 'compagnie',
                    'embarquement.sync.pull' => 'compagnie',
                    'embarquement.sync.push' => 'compagnie',
                    'embarquement.ticket.block' => 'compagnie',
                    'embarquement.ticket.markAbsent' => 'compagnie',
                    'embarquement.ticket.scan' => 'compagnie',
                    'embarquement.ticket.validate' => 'compagnie',
                    'embarquement.ticket.verifyByPhone' => 'compagnie',
                    'guichet.siege.reassign' => 'gare',
                    'guichet.ticket.block' => 'compagnie',
                    'guichet.ticket.view.gare' => 'gare',
                    'reseau.chauffeur.view' => 'compagnie',
                    'reseau.gare.view' => 'compagnie',
                    'reseau.vehicule.view' => 'compagnie',
                    'voyage.instance.close' => 'gare',
                    'voyage.instance.view' => 'gare',
                    'voyage.trajet.view' => 'compagnie',
                    'voyage.voyage.view' => 'gare',
                ],
            ],
            [
                'name' => 'bagagiste',
                'label' => 'Bagagiste',
                'scope' => 'compagnie',
                'rang' => 20,
                'description' => 'Enregistrement des bagages et du fret.',
                'permissions' => [
                    'compagnie.profil.view' => 'compagnie',
                    'embarquement.app.login' => 'compagnie',
                    'embarquement.bagage.register' => 'compagnie',
                    'embarquement.manifeste.view' => 'compagnie',
                    'embarquement.sync.pull' => 'compagnie',
                    'embarquement.sync.push' => 'compagnie',
                    'guichet.ticket.view.gare' => 'gare',
                    'reseau.gare.view' => 'compagnie',
                    'reseau.vehicule.view' => 'compagnie',
                    'voyage.instance.view' => 'gare',
                    'voyage.trajet.view' => 'compagnie',
                    'voyage.voyage.view' => 'gare',
                ],
            ],
            [
                'name' => 'chef_parc',
                'label' => 'Chef de Parc',
                'scope' => 'compagnie',
                'rang' => 50,
                'description' => 'Parc roulant : véhicules, entretien, pièces et documents du matériel.',
                'permissions' => [
                    'compagnie.dashboard.view' => 'compagnie',
                    'compagnie.parametres.view' => 'compagnie',
                    'compagnie.profil.view' => 'compagnie',
                    'compagnie.user.view' => 'compagnie',
                    'finance.depense.create' => 'compagnie',
                    'finance.depense.view' => 'compagnie',
                    'finance.rapport.view' => 'compagnie',
                    'reseau.chauffeur.create' => 'compagnie',
                    'reseau.chauffeur.delete' => 'compagnie',
                    'reseau.chauffeur.update' => 'compagnie',
                    'reseau.chauffeur.view' => 'compagnie',
                    'reseau.document.delete' => 'compagnie',
                    'reseau.document.manageRappel' => 'compagnie',
                    'reseau.document.upload' => 'compagnie',
                    'reseau.document.view' => 'compagnie',
                    'reseau.gare.view' => 'compagnie',
                    'reseau.vehicule.create' => 'compagnie',
                    'reseau.vehicule.delete' => 'compagnie',
                    'reseau.vehicule.setStatut' => 'compagnie',
                    'reseau.vehicule.update' => 'compagnie',
                    'reseau.vehicule.view' => 'compagnie',
                    'voyage.instance.assignChauffeur' => 'compagnie',
                    'voyage.instance.assignVehicule' => 'compagnie',
                    'voyage.instance.view' => 'compagnie',
                    'voyage.trajet.view' => 'compagnie',
                    'voyage.voyage.view' => 'compagnie',
                ],
            ],
            [
                'name' => 'comptable',
                'label' => 'Comptabilité',
                'scope' => 'compagnie',
                'rang' => 60,
                'description' => 'Tenue des comptes, rapports, arbitrage des conflits d\'embarquement.',
                'permissions' => [
                    'caisse.ecart.validate' => 'compagnie',
                    'caisse.historique.export' => 'compagnie',
                    'caisse.historique.view' => 'compagnie',
                    'caisse.session.view.all' => 'compagnie',
                    'caisse.session.view.gare' => 'gare',
                    'compagnie.dashboard.view' => 'compagnie',
                    'compagnie.parametres.view' => 'compagnie',
                    'compagnie.profil.view' => 'compagnie',
                    'compagnie.user.view' => 'compagnie',
                    'crm.fidelite.adjust' => 'compagnie',
                    'crm.fidelite.view' => 'compagnie',
                    'embarquement.conflit.resolve' => 'compagnie',
                    'embarquement.conflit.view' => 'compagnie',
                    'embarquement.manifeste.view' => 'compagnie',
                    'finance.bilan.view' => 'compagnie',
                    'finance.categorie.manage' => 'compagnie',
                    'finance.depense.create' => 'compagnie',
                    'finance.depense.delete' => 'compagnie',
                    'finance.depense.update' => 'compagnie',
                    'finance.depense.view' => 'compagnie',
                    'finance.promo.create' => 'compagnie',
                    'finance.promo.deactivate' => 'compagnie',
                    'finance.promo.update' => 'compagnie',
                    'finance.promo.view' => 'compagnie',
                    'finance.rapport.export' => 'compagnie',
                    'finance.rapport.view' => 'compagnie',
                    'finance.recette.create' => 'compagnie',
                    'finance.recette.delete' => 'compagnie',
                    'finance.recette.update' => 'compagnie',
                    'finance.recette.view' => 'compagnie',
                    'finance.remboursement.approve' => 'compagnie',
                    'finance.remboursement.request' => 'compagnie',
                    'guichet.ticket.block' => 'compagnie',
                    'guichet.ticket.cancel' => 'compagnie',
                    'guichet.ticket.export' => 'compagnie',
                    'guichet.ticket.unblock' => 'compagnie',
                    'guichet.ticket.view.all' => 'compagnie',
                    'guichet.ticket.view.gare' => 'gare',
                    'reseau.chauffeur.view' => 'compagnie',
                    'reseau.document.view' => 'compagnie',
                    'reseau.gare.view' => 'compagnie',
                    'reseau.vehicule.view' => 'compagnie',
                    'voyage.instance.view' => 'compagnie',
                    'voyage.trajet.view' => 'compagnie',
                    'voyage.voyage.view' => 'compagnie',
                ],
            ],
            [
                'name' => 'rh',
                'label' => 'Ressources Humaines',
                'scope' => 'compagnie',
                'rang' => 50,
                'description' => 'Personnel et documents du personnel.',
                'permissions' => [
                    'compagnie.dashboard.view' => 'compagnie',
                    'compagnie.gare.assignUser' => 'compagnie',
                    'compagnie.parametres.view' => 'compagnie',
                    'compagnie.profil.view' => 'compagnie',
                    'compagnie.user.create' => 'compagnie',
                    'compagnie.user.disable' => 'compagnie',
                    'compagnie.user.resetPassword' => 'compagnie',
                    'compagnie.user.update' => 'compagnie',
                    'compagnie.user.view' => 'compagnie',
                    'finance.depense.create' => 'compagnie',
                    'finance.depense.view' => 'compagnie',
                    'finance.rapport.view' => 'compagnie',
                    'reseau.chauffeur.create' => 'compagnie',
                    'reseau.chauffeur.delete' => 'compagnie',
                    'reseau.chauffeur.update' => 'compagnie',
                    'reseau.chauffeur.view' => 'compagnie',
                    'reseau.document.delete' => 'compagnie',
                    'reseau.document.manageRappel' => 'compagnie',
                    'reseau.document.upload' => 'compagnie',
                    'reseau.document.view' => 'compagnie',
                    'reseau.gare.view' => 'compagnie',
                ],
            ],
            [
                'name' => 'communication',
                'label' => 'Chargé de Communication',
                'scope' => 'compagnie',
                'rang' => 40,
                'description' => 'Contenu éditorial, annonces de service et animation des avis clients.',
                'permissions' => [
                    'compagnie.dashboard.view' => 'compagnie',
                    'compagnie.profil.update' => 'compagnie',
                    'compagnie.profil.view' => 'compagnie',
                    'contenu.article.create' => 'compagnie',
                    'contenu.article.delete' => 'compagnie',
                    'contenu.article.publish' => 'compagnie',
                    'contenu.article.update' => 'compagnie',
                    'contenu.article.view' => 'compagnie',
                    'contenu.categorie.manage' => 'compagnie',
                    'contenu.commentaire.moderate' => 'compagnie',
                    'contenu.tag.manage' => 'compagnie',
                    'crm.conversation.reply' => 'compagnie',
                    'crm.conversation.view' => 'compagnie',
                    'crm.rating.reply' => 'compagnie',
                    'crm.rating.report' => 'compagnie',
                    'crm.rating.view' => 'compagnie',
                    'finance.promo.create' => 'compagnie',
                    'finance.promo.deactivate' => 'compagnie',
                    'finance.promo.update' => 'compagnie',
                    'finance.promo.view' => 'compagnie',
                    'reseau.gare.view' => 'compagnie',
                    'voyage.trajet.view' => 'compagnie',
                    'voyage.voyage.view' => 'compagnie',
                ],
            ],
            [
                'name' => 'service_client',
                'label' => 'Service Client',
                'scope' => 'compagnie',
                'rang' => 40,
                'description' => 'Conversations, avis, signalements et réclamations des voyageurs.',
                'permissions' => [
                    'client.fidelite.view.own' => 'own',
                    'client.profil.view' => 'compagnie',
                    'client.ticket.changeDate' => 'compagnie',
                    'client.ticket.pause' => 'compagnie',
                    'client.ticket.pdf' => 'compagnie',
                    'client.ticket.regenerate' => 'compagnie',
                    'client.ticket.transfer' => 'compagnie',
                    'client.ticket.view.own' => 'own',
                    'compagnie.dashboard.view' => 'compagnie',
                    'compagnie.profil.view' => 'compagnie',
                    'contenu.article.view' => 'compagnie',
                    'contenu.commentaire.moderate' => 'compagnie',
                    'crm.bugreport.triage' => 'compagnie',
                    'crm.bugreport.view' => 'compagnie',
                    'crm.conversation.assign' => 'compagnie',
                    'crm.conversation.close' => 'compagnie',
                    'crm.conversation.reply' => 'compagnie',
                    'crm.conversation.view' => 'compagnie',
                    'crm.fidelite.view' => 'compagnie',
                    'crm.rating.reply' => 'compagnie',
                    'crm.rating.report' => 'compagnie',
                    'crm.rating.view' => 'compagnie',
                    'embarquement.conflit.view' => 'compagnie',
                    'embarquement.manifeste.view' => 'compagnie',
                    'embarquement.ticket.verifyByPhone' => 'compagnie',
                    'finance.promo.view' => 'compagnie',
                    'finance.remboursement.request' => 'compagnie',
                    'guichet.reservation.hold' => 'compagnie',
                    'guichet.ticket.cancel' => 'compagnie',
                    'guichet.ticket.changeDate' => 'compagnie',
                    'guichet.ticket.pause' => 'compagnie',
                    'guichet.ticket.print' => 'compagnie',
                    'guichet.ticket.reprint' => 'compagnie',
                    'guichet.ticket.transfer' => 'compagnie',
                    'guichet.ticket.view.all' => 'compagnie',
                    'guichet.ticket.view.gare' => 'gare',
                    'reseau.gare.view' => 'compagnie',
                    'voyage.instance.view' => 'compagnie',
                    'voyage.trajet.view' => 'compagnie',
                    'voyage.voyage.view' => 'compagnie',
                ],
            ],
            [
                'name' => 'auditeur',
                'label' => 'Auditeur',
                'scope' => 'compagnie',
                'rang' => 40,
                'description' => 'Contrôle de gestion en lecture seule. Ne porte aucune permission d\'écriture.',
                'permissions' => [
                    'caisse.historique.export' => 'compagnie',
                    'caisse.historique.view' => 'compagnie',
                    'caisse.session.view.all' => 'compagnie',
                    'caisse.session.view.gare' => 'gare',
                    'compagnie.dashboard.view' => 'compagnie',
                    'compagnie.parametres.view' => 'compagnie',
                    'compagnie.profil.view' => 'compagnie',
                    'compagnie.user.view' => 'compagnie',
                    'contenu.article.view' => 'compagnie',
                    'crm.bugreport.view' => 'compagnie',
                    'crm.conversation.view' => 'compagnie',
                    'crm.fidelite.view' => 'compagnie',
                    'crm.rating.view' => 'compagnie',
                    'embarquement.conflit.view' => 'compagnie',
                    'embarquement.manifeste.view' => 'compagnie',
                    'finance.bilan.view' => 'compagnie',
                    'finance.depense.view' => 'compagnie',
                    'finance.promo.view' => 'compagnie',
                    'finance.rapport.export' => 'compagnie',
                    'finance.rapport.view' => 'compagnie',
                    'finance.recette.view' => 'compagnie',
                    'guichet.ticket.export' => 'compagnie',
                    'guichet.ticket.view.all' => 'compagnie',
                    'guichet.ticket.view.gare' => 'gare',
                    'reseau.chauffeur.view' => 'compagnie',
                    'reseau.document.view' => 'compagnie',
                    'reseau.gare.view' => 'compagnie',
                    'reseau.vehicule.view' => 'compagnie',
                    'voyage.instance.view' => 'compagnie',
                    'voyage.trajet.view' => 'compagnie',
                    'voyage.voyage.view' => 'compagnie',
                ],
            ],
            [
                'name' => 'chauffeur',
                'label' => 'Chauffeur',
                'scope' => 'compagnie',
                'rang' => 10,
                'description' => 'Accès restreint à ses propres affectations et à ses documents.',
                'permissions' => [
                    'compagnie.profil.view' => 'compagnie',
                    'embarquement.manifeste.view' => 'own',
                    'reseau.document.view' => 'own',
                    'reseau.gare.view' => 'compagnie',
                    'reseau.vehicule.view' => 'own',
                    'voyage.instance.view' => 'own',
                    'voyage.trajet.view' => 'compagnie',
                    'voyage.voyage.view' => 'own',
                ],
            ],
        ];
    }

    /** Noms des dix-neuf rôles gabarits. */
    public static function noms(): array
    {
        return array_column(self::tous(), 'name');
    }

    /** Un gabarit par son nom. */
    public static function parNom(string $nom): ?array
    {
        foreach (self::tous() as $gabarit) {
            if ($gabarit['name'] === $nom) {
                return $gabarit;
            }
        }

        return null;
    }

    /** Rang d'un rôle gabarit, 0 si inconnu. */
    public static function rang(string $nom): int
    {
        return self::parNom($nom)['rang'] ?? 0;
    }
}
